### ISSUE TITLE
question:Where is Parser.h?

### ISSUE THREAD

**Issue by Ironlenny** [sharemind-sdk/secrec#1]
I've searched through all the sharemind repos, and I cannot find Parser.h. Where is it? Is it a generated file? If so when is it generated?

**Comment by Jaak** [comment]
You have closed the issue but I'll leave an answer regardless. Many of the headers can be found in the [include](https://github.com/sharemind-sdk/secrec/tree/master/include/libscc) directory. Those are the header files that are also installed. Some of the header files, that should not be installed, are found in the source directory.

If you have questions about the code feel free to ask them personally.
- Jaak
